version: '3'

services:
  node1:
    build:
      dockerfile: Dockerfile
    container_name: node1
    ports:
      - "8080:8080"
    environment:
      ADDRESS: ws://localhost
      PEERS:
      PORT: 8080
    network_mode: host
  node2:
    build:
      dockerfile: Dockerfile
    container_name: node2
    ports:
      - "8081:8081"
    environment:
      ADDRESS: ws://localhost
      PEERS: ws://localhost:8080
      PORT: 8081
    depends_on:
      - node1
    network_mode: host
  node3:
    build:
      dockerfile: Dockerfile
    container_name: node3
    ports:
      - "8082:8082"
    environment:
      ADDRESS: ws://localhost
      PEERS: ws://localhost:8080 ws://localhost:8081
      PORT: 8082
    depends_on:
      - node1
      - node2
    network_mode: host
    